application: mgh-live-en
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  mime_type: text/html; charset=UTF-8
  static_files: static/index.html
  upload: static/index.html
  http_headers:
    Strict-Transport-Security: max-age=10886400; includeSubDomains

- url: /(.*\.html)
  mime_type: text/html; charset=UTF-8
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"
  http_headers:
    Strict-Transport-Security: max-age=10886400; includeSubDomains

- url: /
  static_dir: static

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
