application: mgh-live-nl
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10m"

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
